apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: my-namespace
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
        command:
        - "/cloud_sql_proxy"
        - "-dir=/cloudsql"
        - "-instances=$(INSTANCE_CONNECTION_NAME)=tcp:3306"
        - "-credential_file=/secrets/service_account.json"
        env:
        - name: INSTANCE_CONNECTION_NAME
          value: "capstone-430018:us-central1:telus-itms"
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /cloudsql
        - name: secret-volume
          mountPath: /secrets
      containers:
      - name: backend
        image: azmatpathan/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "/cloudsql/$(INSTANCE_CONNECTION_NAME)"
        - name: DB_USER
          value: "your-cloud-sql-user"
        - name: DB_PASSWORD
          value: "your-cloud-sql-password"
        - name: DB_NAME
          value: "itms"
        - name: INSTANCE_CONNECTION_NAME
          value: "capstone-430018:us-central1:telus-itms"
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /cloudsql
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: service-secret-key
      - name: secret-volume
        secret:
          secretName: service-secret-key
