apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: my-namespace
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: azmatpathan/backend:latest
        ports:
        - containerPort: 5000 # Ensure your backend listens on this port
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          value: "myuser"
        - name: DB_PASSWORD
          value: "mypassword"
        - name: DB_NAME
          value: "mydatabase"
