apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend-tls
  namespace: my-namespace
spec:
  secretName: backend-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: telus-itms.com
  dnsNames:
  - telus-itms.com
